version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=mysql_testing
          - MYSQL_HOST=127.0.0.1
          - MYSQL_USER=bbdeux
          - MYSQL_PASSWORD=password
          - MYSQL_ROOT_HOST=%
    working_directory: ~/bbdeux
    steps:
      - checkout
      - run:
          name: Installing SQLite, ZLIB and PHP dependencies
          command: sudo apt install -y zlib1g-dev ; sudo docker-php-ext-install zip pdo_mysql
      - run:
          name: Updating Composer
          command: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Installing Composer dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run:
          name: Running YARN
          command: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Migrating
          command: php artisan migrate --env=testing --database=mysql_testing --force
      - run:
          name: Running tests
          command: ./vendor/bin/phpunit